### ISSUE TITLE
Bug in JalousieAccessory.js, stuck in opening or closing

### ISSUE THREAD

**Issue by felix-r9** [henry-spanka/homebridge-freeathome#17] opened 2019-11-13 17:52 UTC
Hello Henry,

I've been using your plugin since April, thank you for the awesome work.
However, recently I upgraded my home with the "Sensor/ Jalousieaktor 1/1-fach". Controlling the blinds works flawless. But as soon as I use the switch on the wall to control the blinds, homebridge is not able to calculate the current position (it stucks in "opening" or "closing" with the little circle spinning)

I analyzed it. The problem is the missing target position. While using the switch, the target position keeps the last known value. And because Homekit is comparing target position and current position it will stay in "opening" or "closing" state until you move the blinds with the app.
(I hope you know what I mean :D)

I changed your code to solve the problem. I've been testing the code since 3 days and it works like a charm. Now the target position value is not needed anymore. 
Position state 0 and 1 is stopped --> Target position and current position is the same, so the code provides Homekit the current position as target positon
Position state 2 --> Open blinds so we simply tell Homekit 100 % as target
Position state 3 --> closing blinds so we tell Homekit 0 % as target

each time the movement finishes, we get a 0 or 1 (depending on the movement direction) so the current position can be calculated by Homekit.

I reworked the complete getTargetPosition function:

----------------------------------------
getTargetPosition: function(callback) {
        if (callback) {
          
	   	let posState = this.getValue(this.channel, 'odp0000');
		let posStateLog;

		switch (posState) {

		case '0': // Fallthrough
		case '1':
		callback(null, 100 - parseInt(this.getValue(this.channel, 'odp0001')));
		posStateLog = "STOPPED";
		break;

		case '2':
		callback(null, 100);
		posStateLog = "UP";
		break;

		case '3':
		callback(null, 0);
		posStateLog = "DOWN";	

}
	  
	this.platform.log(this.uuid_base +' Position-State --> ' + posState + ' ' + posStateLog);

          
        }
    },

--------------------------
Maybe you can include it in the next release :)

**Comment by henry-spanka** [comment] 2019-11-13 20:57
Hi,
thanks for reporting this. I will try to reproduce this tomorrow with my shutters.
However I don't think it's a good idea to manually fake the TargetPosition as this may cause unwanted behaviour in HomeKit. What if you only want to set the TargetPosition to 70%? Your patch would only allow 0% or 100% which is not ideal.

**Comment by felix-r9** [comment] 2019-11-13 21:51
Hi,
I did not touch the set target position part, only the get target position. So if you set it to 70 % the shutter moves to that position 😊.
Basically the 0 % and 100 % is just to be sure HomeKit is showing the right state while moving the shutter up or down, regardless from the current position and target position (in my first fix this part was missing and for this, HomeKit didn‘t show „opening“ or „closing“. It simply changed the percentage as soon as it reached the position).
The original code works as long as the movement is triggered by changing the target position (with the set target pos function).

It looks like you are also trying to avoid this problem in your code:
If (targetpos === undefined)...

The problem is, this state never happens, at least with my shutters. As I sad, if I move it by pressing the switch and for this do not provide the system a new target position, the targetpos does not change to undefined, it keeps the last known value.

Short example: 
Targetposition is set to 20, shutter moves to that position. 
Then HomeKit calculates targetpos - actual pos, which is 20 - 20. If the result is 0, HomeKit knows, the shutter has finished it‘a movement.

Next you open the shutter manually by pressing the switch and stop it also by pressing the switch again. The current position is now let’s say 95.
HomeKit calculates again:
Targetpos - actual pos, which is 20 - 95.
Now HomeKit thinks the shutter is currently moving down, as the difference is negative, even the shutter has reached it‘a position.

It‘s so hard to explain in english 😃.

I‘m curious how your shutters perform 😊

**Comment by henry-spanka** [comment] 2019-11-14 11:52
Thanks for the explanation, now I got it. I could reproduce this with my shutters, but I'm pretty sure that it worked before. I think ABB changed their implementation in the past updates.

Your fix looks fine but I don't think it's a good idea to hardcode the TargetPosition to 0% or 100% if you control the shutter with HomeKit. I may confuse HomeKit if you set TargetPosition to 30% because the next time HomeKit reads the TargetPosition (while the shutter is still moving) it will be either 0% or 100% which is incorrect.

For reference (shutter manually closed for a short time, then manually stopped):

```json
< {"result":{"ABB***":{"serialNumber":"ABB***","channels":{"ch0003":{"datapoints":{"idp0001":"1"}}},"deviceId":"B001","typeName":"Jalousieaktor 4-fach, REG"},"ABB***":{"serialNumber":"ABB***","channels":{"ch0000":{"datapoints":{"odp0003":"1"}}},"deviceId":"1002","typeName":"Sensoreinheit 2-fach"}},"type":"update"}
< {"result":{"ABB***":{"serialNumber":"ABB***","channels":{"ch0003":{"datapoints":{"odp0000":"3"}}},"deviceId":"B001","typeName":"Jalousieaktor 4-fach, REG"}},"type":"update"}
< {"result":{"ABB***":{"serialNumber":"ABB***","channels":{"ch0003":{"datapoints":{"idp0001":"0"}}},"deviceId":"B001","typeName":"Jalousieaktor 4-fach, REG"},"ABB***":{"serialNumber":"ABB***","channels":{"ch0000":{"datapoints":{"odp0003":"0"}}},"deviceId":"1002","typeName":"Sensoreinheit 2-fach"}},"type":"update"}
< {"result":{"ABB***":{"serialNumber":"ABB***","channels":{"ch0003":{"datapoints":{"odp0000":"1","odp0001":"11"}}},"deviceId":"B001","typeName":"Jalousieaktor 4-fach, REG"}},"type":"update"}
```

I think we should do the following to fix this:
1. Add listener for PositionState

**Comment by bkniffler** [comment] 2020-05-31 09:01
Heya, I've been using @felix-r9 snippet above and it worked solidly. Could we, until theres been something better worked out, have that released? I wouldn't mind creating a PR if that helped.

**Comment by bkniffler** [comment] 2020-05-31 09:29
Here is the function formatted (credits to @felix-r9)
```js
getTargetPosition: function(callback) {
  if (callback) {
    let posState = this.getValue(this.channel, 'odp0000');
    let posStateLog;

    switch (posState) {
      case '0': // Fallthrough
      case '1':
        callback(null, 100 - parseInt(this.getValue(this.channel, 'odp0001')));
        posStateLog = 'STOPPED';
        break;

      case '2':
        callback(null, 100);
        posStateLog = 'UP';
        break;

      case '3':
        callback(null, 0);
        posStateLog = 'DOWN';
    }
    this.platform.log(
      this.uuid_base + ' Position-State --> ' + posState + ' ' + posStateLog
    );
  }
}
```

**Comment by henry-spanka** [comment] 2022-02-24 20:29
Closing this as I couldn't reproduce it. Please open another issue if still relevant.

**Closed by henry-spanka** 2022-02-24 20:29 UTC
Labels: bug
